name: backend - api
on: [push]
defaults:
  run:
    working-directory: ./backend/api
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Lint with Checkstyle
        run: mvn checkstyle:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Start services
        run: docker compose up -d
      - name: Wait for the containers
        run: sleep 10s
      - name: Unit test with JUnit
        run: mvn test
